[colors.primary]
background = "#0a0607"
foreground = "#a8a6a7"
dim_foreground = "#a0a0a0"
bright_foreground = "#a8a6a7"

[colors.cursor]
text = "#140d0e"
cursor = "#a8a6a7"

[colors.vi_mode_cursor]
text = "#140d0e"
cursor = "#a8a6a7"

[colors.search.matches]
foreground = "#140d0e"
background = "#a8a6a7"

[colors.search.focused_match]
foreground = "#140d0e"
background = "#a8a6a7"

[colors.footer_bar]
foreground = "#140d0e"
background = "#a8a6a7"

[colors.hints.start]
foreground = "#140d0e"
background = "#FFFF00"

[colors.hints.end]
foreground = "#140d0e"
background = "#a8a6a7"

[colors.selection]
text = "#140d0e"
background = "#a8a6a7"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a8a6a7"

[colors.bright]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a0a0a0"


[[colors.indexed_colors]]
index = 16
color = "#140d0e"

[[colors.indexed_colors]]
index = 17
color = "#a8a6a7"
