[colors.primary]
background = "#050304"
foreground = "#846677"
dim_foreground = "#a0a0a0"
bright_foreground = "#846677"

[colors.cursor]
text = "#050304"
cursor = "#846677"

[colors.vi_mode_cursor]
text = "#050304"
cursor = "#846677"

[colors.search.matches]
foreground = "#050304"
background = "#846677"

[colors.search.focused_match]
foreground = "#050304"
background = "#846677"

[colors.footer_bar]
foreground = "#050304"
background = "#846677"

[colors.hints.start]
foreground = "#050304"
background = "#FFFF00"

[colors.hints.end]
foreground = "#050304"
background = "#846677"

[colors.selection]
text = "#050304"
background = "#846677"

[colors.normal]
black   = "#846677"
red     = "#b2313a"
green   = "#488723"
yellow  = "#b07f2c"
blue    = "#5f68c6"
magenta = "#c1558e"
cyan    = "#308188"
white   = "#a8a6a7"

[colors.bright]
black   = "#93717c"
red     = "#ba5f48"
green   = "#429637"
yellow  = "#b7ab42"
blue    = "#8b7ed6"
magenta = "#d2738b"
cyan    = "#5085a0"
white   = "#b7b5b6"


[[colors.indexed_colors]]
index = 16
color = "#050304"

[[colors.indexed_colors]]
index = 17
color = "#846677"
