[colors.primary]
background = "#000000"
foreground = "#b1b1b1"
dim_foreground = "#a0a0a0"
bright_foreground = "#b1b1b1"

[colors.cursor]
text = "#000000"
cursor = "#b1b1b1"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#b1b1b1"

[colors.search.matches]
foreground = "#000000"
background = "#b1b1b1"

[colors.search.focused_match]
foreground = "#000000"
background = "#b1b1b1"

[colors.footer_bar]
foreground = "#000000"
background = "#b1b1b1"

[colors.hints.start]
foreground = "#000000"
background = "#FFFF00"

[colors.hints.end]
foreground = "#000000"
background = "#b1b1b1"

[colors.selection]
text = "#000000"
background = "#b1b1b1"

[colors.normal]
black   = "#2B2B2B"
red     = "#c15563"
green   = "#8ec155"
yellow  = "#c18755"
blue    = "#558ec1"
magenta = "#c1558e"
cyan    = "#55c187"
white   = "#8d7b83"

[colors.bright]
black   = "#2B2B2B"
red     = "#cc5649"
green   = "#29994a"
yellow  = "#c0a24b"
blue    = "#5c97db"
magenta = "#c1558e"
cyan    = "#2d9ead"
white   = "#8d7b83"


[[colors.indexed_colors]]
index = 16
color = "#000000"

[[colors.indexed_colors]]
index = 17
color = "#b1b1b1"
