[colors.primary]
background = "#000000"
foreground = "#b1b1b1"
dim_foreground = "#a0a0a0"
bright_foreground = "#b1b1b1"

[colors.cursor]
text = "#000000"
cursor = "#b1b1b1"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#b1b1b1"

[colors.search.matches]
foreground = "#000000"
background = "#b1b1b1"

[colors.search.focused_match]
foreground = "#000000"
background = "#b1b1b1"

[colors.footer_bar]
foreground = "#000000"
background = "#b1b1b1"

[colors.hints.start]
foreground = "#000000"
background = "#FFFF00"

[colors.hints.end]
foreground = "#000000"
background = "#b1b1b1"

[colors.selection]
text = "#000000"
background = "#b1b1b1"

[colors.normal]
black = "#4C4A48"
red = "#C45B67"
green = "#4F8F65"
yellow = "#D7B55F"
blue = "#4C89B5"
magenta = "#C1558E"
cyan = "#4E9AA7"
white = "#b1b1b1"

[colors.bright]
black = "#4C4A48"
red = "#C45B67"
green = "#4F8F65"
yellow = "#D7B55F"
blue = "#4C89B5"
magenta = "#C1558E"
cyan = "#4E9AA7"
white = "#b1b1b1"

[[colors.indexed_colors]]
index = 16
color = "#000000"

[[colors.indexed_colors]]
index = 17
color = "#b1b1b1"
